# This affects access control for clients with no username.
# unregistered devices dont use username
topic write tele/#

# This only affects clients with USERNAME "roger".
#user roger
#topic foo/bar
user monitor
topic #
topic read $SYS/#

# NRG Optimizer components
# nrg-stats subscriber collects new device appearance and power consumption stats from registered devices
user nrg-stats
topic read tele/#
topic read stat/#

# nrg-webapp programs and controls all devices
user nrg-webapp
topic write cmnd/#
topic read stat/#

# nrg-scheduler publishes on group control channels 
user nrg-scheduler
topic write cmnd/schedule/#

# This affects all CLIENTS.
#pattern write $SYS/broker/connection/%c/state

# devices can push to user subchannels
pattern write tele/%u/#
pattern write stat/%u/#
# devices can subscribe to idirecy command channels
pattern read cmnd/%u/#
# devices belonging to users with subscription can lister schedules
pattern read cmnd/schedule/#

